チャット機能ビュー作成
mirion615/git-sample pull request #27
Opened 2021-06-25 07:04 UTC by fuosa

# What
チャットルームのビュー作成

# Why
チャット機能を実装するため

2021-06-25 08:55 UTC, mirion615 commented on app/views/layouts/chat_room/show.html.erb
> +  <% end %>
重複なので削除ですかね！

2021-06-25 10:31 UTC, mirion615 requested changes
終わりました　よろしくね

2021-06-25 10:31 UTC, mirion615 commented on app/views/layouts/chat_room/show.html.erb
> +  <% end %>
げっげげｗｔ

2021-06-25 10:31 UTC, mirion615 commented on app/assets/stylesheets/chat_room.css
> +
いじおｋ

2021-06-30 01:35 UTC, takeuchitakumi commented
LGBTです！

2021-06-30 07:27 UTC, merged